### ISSUE TITLE
Cloud save fails every time I load the app

### ISSUE THREAD

**Issue by draco121088** [G-Goldstein/The-Great-Outdoors-Issues#2]
Howdy! 

Just FYI every time I load up the app it asks me to select my google play account, then the local save loads ok but the cloud save fails. 

Also, my "google play games" section of the menu says I'm signed in, but nothing happens if I press "achievements" or any of the 3 boards under "leaderboards"?

I'm on 1.0.2

**Comment by G-Goldstein** [comment]
Thanks for reporting. This issue started in Alpha when I introduced cloud save on top of the existing Google Play Games functionality, and it should only affect Alpha testers.

To fix, you can find the Play Games app, go to App Info > Storage > Clear cache. This might sign you out of Google Play Games on all your apps, but you won't lose any progress. You should then be able to sign in and have it work.

If this doesn't fix it, you might need to take the slightly more drastic step of clearing the data on the Play Games app. This will definitely sign you out of your games, but you still won't lose any data.

**Comment by draco121088** [comment]
Cheers for the steps! Didn't actually work for me straight away. 

I then went into Great Outdoors and signed out of my Google Play account, then signed back in within Great Outdoors. That seems to have fixed it.

Issue is resolved for me.
